### ISSUE TITLE
what type of encoder?

### ISSUE THREAD

**Issue by lbernstone** [imxieyi/esp32-rotary-encoder#1]
I am trying to use this library with a rotary encoder on an ESP32.  I don't seem to be getting any interrupts or response of any sort.  I have the encoder set up with 10K resistor pullups.  Is this the configuration you are expecting?

**Comment by imxieyi** [comment]
What encoder are you using?
It works on [25GA20E260](https://www.aliexpress.com/item/Most-delicate-self-balancing-car-motor-with-encoder-DC-gear-Encoder-speed-Smart-home-balancing-trolley/32652688943.html) motor with rotary encoder.
I would recommend using an oscilloscope to monitor the output from the encoder. Pay attention to the voltage of both high level and low level outputs.

**Comment by lbernstone** [comment]
It was totally user error.  Thanks for the response.
